# Generated by Django 3.1.5 on 2022-10-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='title',
        ),
    ]
