# Generated by Django 3.1.5 on 2022-10-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0002_auto_20221031_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='descr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='scan',
            field=models.FileField(null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='doc',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
