# Generated by Django 3.1.5 on 2022-11-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0003_auto_20221031_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
