# Generated by Django 3.1.5 on 2022-11-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0004_auto_20221111_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
