# Generated by Django 3.1.5 on 2022-12-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0009_auto_20221208_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='scan',
            field=models.FileField(null=True, upload_to='docs/'),
        ),
    ]
